### ISSUE TITLE
unable to deploy if 2 factor auth is enabled on github

### ISSUE THREAD

**Issue by yangcheng** [axitkhurana/buster#40]
failed with following 

```
Traceback (most recent call last):
  File "/usr/local/bin/buster", line 9, in <module>
    load_entry_point('buster==0.1.3', 'console_scripts', 'buster')()
  File "/usr/local/lib/python2.7/site-packages/buster/buster.py", line 149, in main
    repo.active_branch.name])
  File "/usr/local/lib/python2.7/site-packages/git/cmd.py", line 377, in execute
    raise GitCommandError(command, status, stderr_value)
git.exc.GitCommandError: 'git push -u origin master' returned exit status 128: remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/yangcheng/yangcheng.github.io/'
```

**Comment by yangcheng** [comment]
need to use token as password. https://github.com/blog/1614-two-factor-authentication
