### ISSUE TITLE
fixlinks error?

### ISSUE THREAD

**Issue by tomvo** [axitkhurana/buster#43]
I get this error when I try to generate the static version.

```
Traceback (most recent call last):
  File "/usr/local/bin/buster", line 9, in <module>
    load_entry_point('buster==0.1.3', 'console_scripts', 'buster')()
  File "/Library/Python/2.7/site-packages/buster/buster.py", line 90, in main
    newtext = fixLinks(filetext, parser)
  File "/Library/Python/2.7/site-packages/buster/buster.py", line 68, in fixLinks
    if not abs_url_regex.search(href):
TypeError: expected string or buffer
```

Any idea?

**Comment by tomvo** [comment]
you need a log file for this maybe?

**Comment by dataaa** [comment]
I also get this issue.

**Comment by apandichi** [comment]
In my case, href was None because it was missing for such an element:

```
  <a><i class="icon icon-list"/></a>
```

EDIT: There's also this pull request with the same fix: https://github.com/axitkhurana/buster/pull/65

**Comment by jitendravyas** [comment]
I'm getting same issue. I'm on Yosemite, python 2.7 and wget 1.16.3

**Comment by sebastianruder** [comment]
Having the same issue. Would be great if one of the above pull requests could be merged, so that we can at least download the current version from GitHub.

**Comment by mlvea** [comment]
Is the issue still persist? I see the last commit in 2014.
