### ISSUE TITLE
Windows bug: unable to run buster setup

### ISSUE THREAD

**Issue by ghost** [axitkhurana/buster#62]
I installed buster on Windows 7 64 bit with Python 2.7.9. But when I try to setup buster with my GitHub repository link, it fails. Below is the stacktrace:

> > Traceback (most recent call last):
> >   File ".\buster.py", line 201, in <module>
> >     main()
> >   File ".\buster.py", line 161, in main
> >     repo = Repo.init(static_path)
> >   File "C:\Python27\lib\site-packages\git\repo\base.py", line 656, in init
> >     output = git.init(*_kwargs)
> >   File "C:\Python27\lib\site-packages\git\cmd.py", line 227, in <lambda>
> >     return lambda *args, *_kwargs: self._call_process(name, _args, *_kwargs)
> >   File "C:\Python27\lib\site-packages\git\cmd.py", line 456, in _call_process
> >     return self.execute(call, *__kwargs)
> >   File "C:\Python27\lib\site-packages\git\cmd.py", line 335, in execute
> >     *_subprocess_kwargs
> >   File "C:\Python27\lib\subprocess.py", line 710, in __init__
> >     errread, errwrite)
> >   File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
> >     startupinfo)
> > WindowsError: [Error 2] The system cannot find the file specified

I have tried to run the python file directly, I get the same error. I also tried this fork - https://github.com/Misiur/buster, still does not work.

**Comment by sebie** [comment]
Check out this issue: #56

**Comment by andreiamlm** [comment]
Hi! I had the same issue on win 10 I solved it like this: 
![txanan](https://cloud.githubusercontent.com/assets/8266900/9609067/8258fdf8-50c9-11e5-9d4a-6e90c1965367.png)

hope it works!
