### ISSUE TITLE
error buster deploy

### ISSUE THREAD

**Issue by fecalemos** [axitkhurana/buster#74]
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\buster.exe__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\buster\buster.py", line 141, in main
    repo = Repo(static_path)
  File "c:\python27\lib\site-packages\git\repo\base.py", line 122, in **init**
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: C:\Users\Fernando\Git\GitHub\blogs\static

I have buster version 0.1.3 e python version 2.7.10

**Comment by Loyalsoldier** [comment]
Try to use this fork: https://github.com/Misiur/buster
