### ISSUE TITLE
Buster setup command not found

### ISSUE THREAD

**Issue by elmehdiceo** [axitkhurana/buster#79]
Hello, i have pip and node installed, buster also however when i try to run this command "buster setup" its not found, any suggestion please ?

Thanks

**Comment by elmehdiceo** [comment]
##Here is my buster issue console 

TypeError: Cannot read property '--port' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/buster/node_modules/buster-server-cli/lib/server-cli.js:47:35)
    at Object.<anonymous> (/usr/local/lib/node_modules/buster/node_modules/buster-cli/lib/buster-cli.js:55:13)
    at Object.module.exports.parse (/usr/local/lib/node_modules/buster/node_modules/posix-argv-parser/lib/posix-argv-parser.js:68:13)
    at Object.module.exports.bane.createEventEmitter.parseArgs (/usr/local/lib/node_modules/buster/node_modules/buster-cli/lib/buster-cli.js:49:19)
    at Object.module.exports.ServerCli.run (/usr/local/lib/node_modules/buster/node_modules/buster-server-cli/lib/server-cli.js:44:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/buster/bin/buster-server:11:4)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
