### ISSUE TITLE
Cannot install buster

### ISSUE THREAD

**Issue by kaimakes** [axitkhurana/buster#89]
I am on Arch (Manjaro) and running `sudo pip install buster` causes the following.

```
[yuki@Skarmory-Manjaro ghost]$ sudo pip install buster
[sudo] password for yuki: ------------
Collecting buster
  Using cached buster-0.1.3.tar.gz
Collecting GitPython==0.3.2.RC1 (from buster)
  Using cached GitPython-0.3.2.RC1.tar.gz
Collecting async==0.6.1 (from buster)
  Using cached async-0.6.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-vl71r_nq/async/setup.py", line 24
        print "Ignored failure when building extensions, pure python modules will be used instead"
                                                                                                 ^
    SyntaxError: Missing parentheses in call to 'print'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-vl71r_nq/async/
```

**Comment by yangcheng** [comment]
you need to use python2. try` pip2 install buster `

**Comment by gauravsitlani** [comment]
Is there any way it can be installed with python3?

**Comment by ensarkarabudak** [comment]
I have the same problem. Solution?
