### ISSUE TITLE
raspberry pi buster install error

### ISSUE THREAD

**Issue by Jeongheegenius-zz** [axitkhurana/buster#95]
Hello! I had to install a buster while making a ghost, so I tried to install it, but the following error occurred. How to solve it? Thanks for your help 😭😭

And the Python version is 2.7.18 and the latest version is also installed. The operating system is raspberry pi 4B.

Note: This article was written via Google Translate :)

```
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting buster
  Using cached https://www.piwheels.org/simple/buster/buster-0.1.3-py3-none-any.whl (5.5 kB)
Collecting async==0.6.1
  Using cached async-0.6.1.tar.gz (36 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python3.6 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ldf0dmfw/async_4e5ddbb9379c4cf0bcaed97435d89ffd/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ldf0dmfw/async_4e5ddbb9379c4cf0bcaed97435d89ffd/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-rsmys3ho
       cwd: /tmp/pip-install-ldf0dmfw/async_4e5ddbb9379c4cf0bcaed97435d89ffd/
  Complete output (6 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-ldf0dmfw/async_4e5ddbb9379c4cf0bcaed97435d89ffd/setup.py", line 24
      print "Ignored failure when building extensions, pure python modules will be used instead"
                                                                                               ^
  SyntaxError: Missing parentheses in call to 'print'. Did you mean print(nt "Ignored failure when building extensions, pure python modules will be used instead")?
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/3a/30/0f97c2e4563bcefaf050b81b300859092c1e003db4f8664a7709fe99ace0/async-0.6.1.tar.gz#sha256=41d14cc0456e03f34d13af284f65821d07d05c20e621bcaebd38f9ab5095d5d1 (from https://pypi.org/simple/async/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Collecting buster
  Using cached https://www.piwheels.org/simple/buster/buster-0.1.2-py3-none-any.whl (4.9 kB)
  Using cached https://www.piwheels.org/simple/buster/buster-0.1.1-py3-none-any.whl (4.7 kB)
  Using cached https://www.piwheels.org/simple/buster/buster-0.1-py3-none-any.whl (4.7 kB)
ERROR: Cannot install buster==0.1, buster==0.1.1, buster==0.1.2 and buster==0.1.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    buster 0.1.3 depends on async==0.6.1
    buster 0.1.2 depends on async==0.6.1
    buster 0.1.1 depends on async==0.6.1
    buster 0.1 depends on async==0.6.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

**Comment by Jeongheegenius-zz** [comment]
I didn't come up with a workaround so I ended up installing it in docker. If you are having the same problem as me, please install it with docker.
